### PR TITLE
New global text replacing

### PR DESCRIPTION
**Pull request by Icelys**
Easier in my opinion. Someone approve please, I did this a bit quick :package:

### CODE REVIEW

**Comment by bjskistad** [comment]
Looks good to me. But I would get someone who knows Node.js better to approve too. :P

**Comment by Jonathan50** [comment]
Why is it called `contentReplace` when it's not just for replacing `{{ content }}`?

**Comment by as-com** [comment]
Looks good to me, but ideally we should do templating in a more efficient manner. What I see right now is quite inefficient.

**Comment by bjskistad** [comment]
@as-com We can edit the code when we accept the PR.

**Comment by bjskistad** [comment]
Should we accept?

**Comment by Jonathan50** [comment]
¯\_(ツ)_/¯ Looks okay

**Comment by bjskistad** [comment]
Merged.

**Comment by Jonathan50** [comment]
Delete branch?

**Comment by Icelys** [comment]
I'm working on re arranging the pages, if we don't want them in the assets folder.

**Comment by Jonathan50** [comment]
Do it in a new branch, then. Is it okay if I delete the branch?

**Comment by Icelys** [comment]
should be.

**Comment by Icelys** [comment]
My first contribution to this :+1:

**Comment by bjskistad** [comment]
@Icelys :confetti_ball:

**Comment by Jonathan50** [comment]
:tada:

**Pull request merged**
